[package]
name = "utc_update_server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
futures-util = "0.3.31"
serde = "1.0.213"
serde_json = "1.0.132"
tokio = "1.41.0"
tokio-tungstenite = "0.24.0"
warp = "0.3.7"
