name: "Release"

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Delete Release
        id: delete_release
        run: |
          RELEASE_NAME="latest"  # Change this to your release name

          # Delete the release
          gh release delete "$RELEASE_NAME" --yes || echo "Release not found"

          # Delete the tag
          git tag -d "$RELEASE_NAME" || echo "Tag not found"
          git push origin :refs/tags/"$RELEASE_NAME" || echo "Remote tag not found"

      - name: Create Release Tag
        id: tag
        run: |
          VERSION="latest"
          echo "TAG=$VERSION" >> $GITHUB_ENV
          git tag $VERSION
          git push origin $VERSION

      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}  # Using tag_name here
          name: "Latest"    # Updated release name
          body: |
            This release includes the latest build of the server.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
