name: "Build && Release"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: CLIENT Build with Cargo
        run: cd ./client && cargo build --release

      - name: SERVER Build with Cargo
        run: cd ./server && cargo build --release

      - name: Create Release Tag
        id: tag
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S') # or set this to your versioning strategy
          echo "TAG=$VERSION" >> $GITHUB_ENV
          git tag $VERSION
          git push origin $VERSION

      - name: Upload build artifact to release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ env.TAG }}
          files: target/release/server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
