name: "Build & Release"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: SERVER Build with Cargo
        run: cd ./server && cargo build --release
        
      - name: CLIENT Build with Cargo
        run: cd ./client && cargo build --release

      - name: List Build Artifacts
        run: |
          echo "Listing server build artifacts:"
          ls ./server/target/release/
          echo "Listing client build artifacts:"
          ls ./client/target/release/

      - name: Create Release Tag
        id: tag
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S') # Set your versioning strategy
          echo "TAG=$VERSION" >> $GITHUB_ENV
          git tag $VERSION
          git push origin $VERSION

      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}  # Using tag_name here
          name: "Release ${{ env.TAG }}"    # Updated release name
          body: |
            This release includes the latest build of the server.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifact to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}  # Using tag_name here
          files: |
            ./server/target/release/utc_update_server
            ./client/target/release/utc_update_client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
